### PR TITLE
Fixed accidental deletion of referenced cached rows when emptyResultSet is called

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
Fixed cause of #187

### CODE REVIEW

**Comment by dg** [comment]
Wow, thanks!

**Comment by MartinMystikJonas** [comment]
@Unlink This fix causes test deleteCahceBug to fail. But I'm not sure what exactly is tested on line 61 where exception is thrown. Could you please explain if it is problem?

**Comment by MartinMystikJonas** [comment]
@Unlink Nevermind. It failed even before this change.

**Comment by JanTvrdik** [comment]
@MartinMystikJonas May I ask how does the fix work? Why assigning `null` by reference is different to assigning `null` directly?

**Comment by MartinMystikJonas** [comment]
> @MartinMystikJonas May I ask how does the fix work? Why assigning `null` by reference is different to assigning `null` directly?

```php
$cachedRows = [1,2,3];
$rows = &$cachedRows;
$rows = null;
// $rows = null
// $cachedRows = null
```
vs
```php
$cachedRows = [1,2,3];
$rows = &$cachedRows;
$null = null;
$rows = &$null;
// $rows = null
// $cachedRows = [1,2,3]
``

When $rows value is reference to cache and null is assigned then referenced data in cache are corrupted. Assigning new reference moves reference to different location and left cached data intact.

**Pull request merged**
