### PR TITLE
Implement SQL Clause in Where IS NOT NULL

### PR DESCRIPTION
**Pull request by nargotik**
- new feature
- BC break no
- doc PR: nette/docs

### CODE REVIEW

**Comment by dg** [comment]
Please do not reopen new pull request, you can change code via force push.

**Comment by nargotik** [comment]
Sorry about it, i'm kinda noob in Git :)

**Comment by nargotik** [comment]
> Please do not reopen new pull request, you can change code via force push.

Have you view this implementation ?

**Comment by matej21** [comment]
@nargotik test is still missing. 
I think it should be enough if you modify this test: https://github.com/nette/database/blob/8b6230de10ce3821bc223a063ef458b189195a60/tests/Database/SqlPreprocessor.phpt#L101

**Comment by nargotik** [comment]
> @nargotik test is still missing.
> I think it should be enough if you modify this test:
> 
> [database/tests/Database/SqlPreprocessor.phpt](https://github.com/nette/database/blob/8b6230de10ce3821bc223a063ef458b189195a60/tests/Database/SqlPreprocessor.phpt#L101)
> 
> Line 101 in [8b6230d](/nette/database/commit/8b6230de10ce3821bc223a063ef458b189195a60)
> 
>  test(function () use ($preprocessor) { // where

Ok added, test

Failing test from coveralls mentions a file not changed at all :-)
Failing test appveyor is because of dns problem in getcomposer

**Comment by dg** [comment]
Thanks!

**Pull request merged**
