### PR TITLE
Debugger Connection Panel explain block - non breakable spaces

### PR DESCRIPTION
**Pull request by WyskyNet**
Tiny styling fix for explain block in database connection panel...

current
formatted

### CODE REVIEW

**Comment by dg** [comment]
What about add style `#tracy-debug .nette-DbConnectionPanel-explain td { whitespace: pre }`?

**Comment by WyskyNet** [comment]
Hi David,
white-space: pre is usable too, but maybe not supported by older browsers...

**Comment by dg** [comment]
Tracy is for IE10+, so it is not problem.

**Comment by JanTvrdik** [comment]
`white-space: pre` or `white-space: pre-wrap`?

**Comment by WyskyNet** [comment]
Hi,
I am not sure about pre / pre-wrap, because i don't use explain regularly, but if I must select one of them, my choice will be pre (one line for one explain statement) :)

**Comment by repli2dev** [comment]
`pre` seems preferable to me as the `pre-wrap` would wrap the long text into multiple lines where the following lines wouldn't be indented at all destroying the benefits of the indention at all.

**Comment by dg** [comment]
We can try `pre` and in case of troubles replace it with `pre-wrap`

**Pull request closed without merging**
