### PR TITLE
Improved phpstan phpDoc

### PR DESCRIPTION
**Pull request by lulco**
This change could help developers using nette/database with phpstan to avoid error "Negative offset or limit" thrown in drivers

### CODE REVIEW

**Comment by dg** [comment]
`0` is accepted to and is not positive.

**Comment by lulco** [comment]
hm why would I do query with limit 0?

**Comment by MartinMystikJonas** [comment]
> LIMIT 0 quickly returns an empty set. This can be useful for checking the validity of a query. It can also be employed to obtain the types of the result columns if you are using a MySQL API that makes result set metadata available.

https://dev.mysql.com/doc/refman/5.7/en/limit-optimization.html

**Comment by lulco** [comment]
OK, so I've added 0, now it is `positive-int|0`

**Comment by dg** [comment]
Well, there are no `@phpstan-params` annotations in the framework and I'm not sure if this is such an important thing to add it.

**Comment by lulco** [comment]
OK, I understand, but this is something you could write week ago :)

**Pull request closed without merging**
