### PR TITLE
Add custom instances (activeRow, selection, groupedSelection) factory

### PR DESCRIPTION
**Pull request by ricco24**
Added opportunity to add custom instances of ActiveRow, Selection and GroupedSelection for any database table.

In some cases it would be nice to be able to use my own classes as results, where i can implement some custom logic per database table.

### CODE REVIEW

**Comment by Unlink** [comment]
This was rejected manny times - https://github.com/nette/database/issues/90
I don't like this: https://github.com/ricco24/database/commit/62ad5d5fc56d479716784c0d28572f60cc25795c#diff-7364bb7cbe87b830ca11d490619a7ec0R20
imho extending `Selection` / `GroupedSelection` / `ActiveRow` is very bad idea.

**Comment by ricco24** [comment]
Why is extending these base classes bad idea? Is there any side effect that i cannot see?

**Comment by Unlink** [comment]
Because of single responsibility principle, the main purpose these classes is mediation of data from database, not business logic of your application.

**Comment by ricco24** [comment]
I understand this, but with this PR the main purpose is preserved. Registration of instanceFactory is optional. But if you need/want to extend this classes you have this opportunity.

**Comment by f3l1x** [comment]
:+1: for good idea
:-1:  for implementation

**Comment by ricco24** [comment]
@f3l1x  Implementation in this point is only prototype. First, i need feedback if this feature has potencial to be merget into repository or is strictly refused.

**Pull request closed without merging**
