### PR TITLE
Selection: Added implementation of JsonSerializable interface 

### PR DESCRIPTION
**Pull request by norbe**

### CODE REVIEW

**Comment by norbe** [comment]
Is there somethink what should I change?

**Comment by dg** [comment]
Why should Selection implement JsonSerializable?

**Comment by norbe** [comment]
Becouse of #109 (https://github.com/nette/database/blob/master/src/Database/Table/SqlBuilder.php#L216).

**Comment by dg** [comment]
It should be fixed in SqlBuilder.php#L216, isn't it?

**Comment by norbe** [comment]
Ok, It would be better. I will prepare another pull-request

**Comment by dg** [comment]
Thank you

**Pull request closed without merging**
